apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chpa-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chpa-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: cronhpa-controller-manager
  namespace: hpa-system
