apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: cronhpa-controller
    app.kubernetes.io/managed-by: kustomize
  name: chpa-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chpa-manager-role
subjects:
- kind: ServiceAccount
  name: cronhpa-controller-manager
  namespace: hpa-system
