apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cronhpa-controller
    app.kubernetes.io/managed-by: kustomize
  name: cronhpa-controller-manager
  namespace: hpa-system